# 'flattens' - un-reifies - a Linkset's rdf:Statements into normal triples

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT { ?s ?p ?o }
WHERE {
    GRAPH ?g {
        ?x a rdf:Statement ;
           rdf:subject ?s ;
           rdf:predicate ?p ;
           rdf:object ?o .
    }
}
